model:
  load: False
  path: "logs/BetaTCVAE/version_0/Model"

model_params:
  name: 'BetaTCVAE'
  in_channels: 1
  latent_dim: 32
  anneal_steps: 10000
  alpha: 1.
  beta:  6.
  gamma: 1.

data_params:
  data_path: "Data/"
  train_batch_size: 64
  val_batch_size:  64
  patch_size: 28
  num_workers: 4


exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  manual_seed: 1265

trainer_params:
  accelerator: 'gpu'
  devices: [0]
  max_epochs: 15

logging_params:
  save_dir: "logs/"
  name: 'BetaTCVAE'
